variant: fcos
version: 1.4.0
storage:
  files:
    - path: /var/lib/keycloak/keycloak.jks
      mode: 0644
      overwrite: true
      contents:
        local: files/keycloak/keycloak.jks
    
    - path: /etc/default/keycloak
      mode: 0644
      contents:
        inline: |
          TZ=America/Denver
          KEYCLOAK_ADMIN=admin
          KEYCLOAK_ADMIN_PASSWORD=changeme
          KC_HOSTNAME=keycloak.service.example.com
          KC_HOSTNAME_PORT=8443
          KC_HTTP_ENABLED=false
          KC_DB=postgres
          KC_DB_URL_HOST=postgresql.container.example.com
          KC_DB_URL_DATABASE=keycloak-internal
          KC_DB_USERNAME=keycloak
          KC_DB_PASSWORD=keycloak
          # KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/server.keycloak
          # KC_HTTPS_KEY_STORE_PASSWORD=password
